### ISSUE TITLE
Fix plugin name

### ISSUE THREAD

**Issue by ai** [archana-s/postcss-flexbox#4]
This code is wrong:

``` js
postcss.plugin('flexbox',
```

You should use same name as in npm:

``` js
postcss.plugin('postcss-flexbox',
```

BTW, you should use [postcss-plugin-boilerplate](https://github.com/postcss/postcss-plugin-boilerplate) to avoid this small mistakes.

**Comment by archana-s** [comment]
Thanks. I just saw the plugin boiler plate. Fixed the plugin name
