### ISSUE TITLE
Move prefixes to Autoprefixer

### ISSUE THREAD

**Issue by ai** [archana-s/postcss-flexbox#6]
Right now current browsers do not need prefixes for flexbox. So, maybe your plugin should add only final spec properties and prefixes should beAuutoprefixer job, because it adds only actual prefixes.

**Comment by archana-s** [comment]
Safari and IE need the prefixes. I just tested this. I removed a couple of moz specific prefixes I had, which are no longer necessary. 

Do you recommend adding a note on auto-prefixer dependency? I do understand that it is better to maintain the vendor-prefixing in one place,  but I still wonder if its a good idea to have this dependency on this plugin.

**Comment by ai** [comment]
In PostCSS is is easy to adding new plugins. Anyway right now every PostCSS user has Autoprefixer.

So, I think you can miss prefixes at all and even do not have Autoprefixer in dependencies. Just add note, that you recommend Autoprefixer and ask users to put Autoprefixer after you plugin.

**Comment by archana-s** [comment]
Excellent. Makes sense. Done.
